FROM webhippie/ubuntu:20.04-arm64@sha256:d254c0f86de55984986fca1f8938c18ed3d2f52a935efc5b0e4bcaf4fe16e3c2

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
  echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/adoptopenjdk.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y adoptopenjdk-16-hotspot && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
