FROM ghcr.io/dockhippie/ubuntu:20.04-arm64@sha256:1e62b6751cf521d01a9762283c59526f6c3fec36c24ceeefca88c417c9a1a6ec

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
  echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/adoptopenjdk.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y adoptopenjdk-11-hotspot libatomic1 && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
