FROM webhippie/ubuntu:21.04-arm@sha256:a7eb6ecb689dc1ff85fa4762451478c342f8cf393c74a935b78e3c20aa05f946

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
  echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/adoptopenjdk.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y adoptopenjdk-11-hotspot && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
